Controllers/RolesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Blogio.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Blogio.Models;

namespace Blogio.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RolesController : Controller
    {
        private RoleManager<IdentityRole> _roleManager;
        private UserManager<User> _userManager;
        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<User> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            return View(_roleManager.Roles.ToList());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateRoleViewModel model)
        {
            if(!string.IsNullOrEmpty(model.RoleName))
            {
                IdentityResult result = await _roleManager.CreateAsync(new IdentityRole(model.RoleName));
                if(result.Succeeded)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    foreach(var error in result.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }
                }
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            if(role != null)
            {
                IdentityResult result = await _roleManager.DeleteAsync(role);
            }
            return RedirectToAction(nameof(Index));
        }

        public IActionResult UserList()
        {
            return View(_userManager.Users.ToList());
        }

        public async Task<IActionResult> Edit(string userId)
        {
            User user = await _userManager.FindByIdAsync(userId);
            if(user != null)
            {
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                ChangeRoleViewModel model = new ChangeRoleViewModel {
                    UserId = user.Id,
                    UserEmail = user.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }
            return NotFound(user);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string> roles)
        {
            User user = await _userManager.FindByIdAsync(userId);
            if(user != null)
            {
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                var addedRoles = roles.Except(userRoles);
                var removedRoles = roles.Except(roles);

                await _userManager.AddToRolesAsync(user, addedRoles);
                await _userManager.RemoveFromRolesAsync(user, removedRoles);

                return RedirectToAction(nameof(UserList));
            }
            return NotFound();
        }
    }
}

Controllers/WriterController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Blogio.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Blogio.ViewModels;
using System.Diagnostics;

namespace Blogio.Controllers
{
    [Authorize(Roles = "Writer,Admin")]
    public class WriterController : Controller
    {
        private AppDbContext _context;
        private UserManager<User> _userManager;
        private IWebHostEnvironment _webHostEnvironment;

        public WriterController(AppDbContext context, IWebHostEnvironment webHostEnvironment, UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
            _webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index(int page)
        {
            ViewBag.Title = "Blogio Writer";

            List<PostViewModel> posts = new List<PostViewModel>();
            foreach (var post in _context.Posts.ToList())
            {
                posts.Add(
                    new PostViewModel
                    {
                        PostId = post.PostId,
                        Title = post.Title,
                        Text = post.Text,
                        Picture = post.Picture,
                        Date = post.Date,
                        Rating = post.Rating,
                        Author = post.Author
                    }
                );
            }
            var model = new Blogio.PaginatedList
            {
                Posts = posts,
                PageSize = 15,
                CurrentPage = page == 0 ? 1 : page
            };
            return View(model);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(PostViewModel postVM)
        {
            User author = await _userManager.GetUserAsync(HttpContext.User);

            if (author.NickName != null)
            {
                postVM.Author = new Author { NickName = author.NickName };
                if (!_context.Authors.Any(a => a.NickName == author.NickName))
                {
                    _context.Authors.Add(postVM.Author);
                    _context.SaveChanges();
                }
            }

            if (postVM.PreviewPicture != null)
            {
                postVM.Picture = GetPicture(postVM.PreviewPicture);
            }
            if (postVM.Picture == "Wrong Format")
            {
                ModelState.AddModelError("", "Wrong Picture Format (.jpg, .jpeg and .png formats are allowed)");
            }

            if (ModelState.IsValid)
            {

                Post post = new Post
                {
                    Title = postVM.Title,
                    Text = postVM.Text,
                    Picture = postVM.Picture,
                    Date = DateTime.Now,
                    Rating = postVM.Rating,
                    Author = postVM.Author
                };
                _context.Posts.Add(post);
                if (postVM.Author != null)
                {
                    _context.Entry(post.Author).State = EntityState.Unchanged;
                }
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        public async Task<IActionResult> Edit(long id)
        {
            var post = await _context.Posts.FirstOrDefaultAsync(p => p.PostId == id);
            if (post != null)
            {
                return View(
                    new PostViewModel
                    {
                        PostId = post.PostId,
                        Title = post.Title,
                        Text = post.Text,
                        Picture = post.Picture,
                        Date = post.Date,
                        Rating = post.Rating,
                        Author = post.Author
                    }
                );
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(PostViewModel postVM)
        {
            if (ModelState.IsValid)
            {
                if (postVM.PreviewPicture != null)
                {
                    postVM.Picture = GetPicture(postVM.PreviewPicture);
                }
                Post post = new Post
                {
                    PostId = postVM.PostId,
                    Title = postVM.Title,
                    Text = postVM.Text,
                    Picture = postVM.Picture,
                    Date = postVM.Date,
                    Rating = postVM.Rating,
                    Author = postVM.Author
                };
                _context.Update(post);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Delete(long id)
        {
            var post = await _context.Posts.FirstOrDefaultAsync(p => p.PostId == id);
            if (post != null)
            {
                _context.Remove(post);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }

        public IActionResult SearchResult(string searchQuery)
        {
            List<Post> dbposts = (from p in _context.Posts
                                  where (p.Title.Contains(searchQuery) || p.Text.Contains(searchQuery))
                                  select p).ToList();
            if (dbposts != null)
            {
                ViewBag.Title = $"'{searchQuery}' Search Results";

                List<PostViewModel> posts = new List<PostViewModel>();
                foreach (var post in dbposts)
                {
                    posts.Add(
                        new PostViewModel
                        {
                            PostId = post.PostId,
                            Title = post.Title,
                            Text = post.Text,
                            Picture = post.Picture,
                            Date = post.Date,
                            Rating = post.Rating,
                            Author = post.Author
                        }
                    );
                }

                var model = new Blogio.PaginatedList
                {
                    Posts = posts,
                    PageSize = 10,
                    CurrentPage = 1
                };

                return View(nameof(Index), model);
            }
            return NotFound();
        }

        private string? GetPicture(IFormFile picture)
        {
            if (picture != null)
            {
                string[] extensions = { ".jpeg", ".jpg", ".png" };
                foreach (var ext in extensions)
                {
                    if (Path.GetExtension(picture.FileName) == ext)
                    {
                        var downName = Path.Combine(_webHostEnvironment.WebRootPath + "/img/", Path.GetFileName(picture.FileName));
                        picture.CopyTo(new FileStream(downName, FileMode.Create));
                        return Path.Combine("/img/", Path.GetFileName(picture.FileName));
                    }
                }
                return "Wrong Format";
            }
            return null;
        }
    }
}

Views/Writer/Create.cshtml
@using Blogio.ViewModels
@model PostViewModel

<div class="card mt-4">
    <div class="card-body">
        <form asp-action="Create" enctype="multipart/form-data" method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group mb-2">
                <label><h5>Title</h5></label>
                <span class="text-danger" asp-validation-for="Title" style="float: right;"></span>
                <input asp-for="Title" class="form-control" />
            </div>
            <div class="form-group mb-2">
                <label><h5>Text</h5></label>
                <span class="text-danger" asp-validation-for="Text" style="float: right;"></span>
                <textarea asp-for="Text" class="form-control" rows="15"></textarea>
            </div>
            <div class="form-group mb-2">
                <label><h5>Choose a Picture</h5></label><br>
                <input name="PreviewPicture" type="file" class="form-control-file">
            </div>
            <button type="submit" class="btn btn-outline-warning" asp-action="Create">Submit</button>
        </form>
    </div>
</div>

Views/Writer/Edit.cshtml
@using Blogio.ViewModels
@using Blogio.Models
@model PostViewModel

<div class="card mt-4">
    <div class="card-body">
        <form enctype="multipart/form-data" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PostId" />
            <input type="hidden" asp-for="Picture" />
            <div class="form-group mb-2">
                <label><h5>Title</h5></label>
                <span class="text-danger" asp-validation-for="Title" style="float: right;"></span>
                <input asp-for="Title" class="form-control" />
            </div>
            <div class="form-group mb-3">
                <label><h5>Text</h5></label>
                <span class="text-danger" asp-validation-for="Text" style="float: right;"></span>
                <textarea asp-for="Text" class="form-control" rows="15"></textarea>
            </div>
            <div class="form-group mb-2">
                <label><h5>Choose a Picture</h5></label><br>
                <input asp-for="PreviewPicture" type="file" class="form-control-file">
            </div>
            <button asp-action="Edit" type="submit" class="btn btn-outline-warning">Submit</button>
        </form>
    </div>
</div>

Views/Writer/Index.cshtml
@using Blogio.ViewModels
@model Blogio.PaginatedList
@{
    List<PostViewModel> NewModel = Blogio.PaginatedList.UsePagination(Model.Posts, Model.PageSize, Model.CurrentPage);
}

<table class="table mt-4">
    <thead>
        <tr>
            <th>Title</th>
            <th>Text</th>
            <th style="width: 20%;"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (PostViewModel post in NewModel)
        {
            <tr>
                <td>@post.Title</td>
                <td>@(new String(@post.Text.Take(100).ToArray()))...</td>
                <td class="text-center">
                    <form method="post">
                        <a class="btn btn-outline-warning" asp-action="Edit" asp-route-id="@post.PostId">Edit</a>
                        <button method="submit" class="btn btn-outline-danger" asp-action="Delete" asp-route-id="@post.PostId">Delete</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>

<div class="container">
    <div class="row">
        <div class="col-12 m-2">
            <nav aria-label="Page navigation">
                <ul class="pagination justify-content-center">
                    <li class="page-item">
                    <a class="page-link text-dark @Model.DisablePrevButton" aria-label="Previous"                            
                        asp-action="Index" asp-route-page="@(Model.CurrentPage-1)">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                    </li>
                    @for(int i = Model.PageStartNumber(); i <= Model.PageEndNumber(); i++)
                    {
                        <li class="page-item">
                            <a class="page-link @(i == Model.CurrentPage ? "active" : "")" asp-action="Index" asp-route-page="@i">
                                @i
                            </a>
                        </li>
                    }
                    <li class="page-item">
                    <a class="page-link text-dark @Model.DisableNextButton" aria-label="Next"
                        asp-action="Index" asp-route-page="@(Model.CurrentPage+1)">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</div>      

Views/Writer/Preview.cshtml
@using Blogio.ViewModels
@model PostViewModel

<div class="col-9 pt-4">
    <ul class="list-group">        
        <li class="list-group-item">
            <h4>@Model.Title</h4>
        </li>
        <li class="list-group-item">
            <img src="@Model.Picture" class="card-img-top p-4" alt="Sample Image" style="border-radius: 0; width: 90%;">
            <p>@Model.Text</p>
        </li>
    </ul>
    <a class="btn btn-outline-warning" href="javascript:history.go(-1)">Back</a>
</div>

Views/Writer/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/lib/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/bootstrap.changes.css">
    <link rel="stylesheet" href="/css/styles.css">
    <title>@(ViewBag.Title ?? "Blogio")</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" asp-action="Index">Blogio Writer</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link" asp-controller="Home" asp-action="Index">User's View</a>  
                @if(User.IsInRole("Admin"))
                {
                    <a class="nav-link" asp-controller="Roles" asp-action="Index">Manage Roles</a>
                }              
                <a class="nav-link" asp-action="Create">Create New Post</a>
                @if(User.Identity.IsAuthenticated)
                {    
                    <form method="post" asp-controller="Account" asp-action="Logout">
                        <input class="nav-link btn" id="logout" type="submit" value="Log Out"/>
                    </form>
                }
                else
                {
                    <a class="nav-link" asp-controller="Account" asp-action="Login">Log In</a>
                    <a class="nav-link" asp-controller="Account" asp-action="Register">Register</a>
                }   
            </div>
        </div>  
        <form method="get" class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="searchQuery">
            <button class="btn btn-outline-light" type="submit" asp-controller="Writer" asp-action="SearchResult">Search</button>
        </form>
    </div>
    </nav>
    <div class="container">
        <div class="row">
            @RenderBody()
        </div>
    </div>    
</body>
</html>